name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - uses: ./
        name: Run int128/glob-changed-files-action
        id: glob-changed-files
        with:
          paths: |
            :dir/**
          transform: |
            :dir
      - run: |
          while read -r changed_file; do
            echo "$changed_file"
          done <<< "$CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ steps.glob-changed-files.outputs.paths }}

      - uses: ./
        name: Run int128/glob-changed-files-action with paths-fallback
        id: glob-changed-files-paths-fallback
        with:
          paths: |
            :dir/**
          paths-fallback: |
            .github/workflows/**
            src/**
      - run: jq . <<< "$CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ steps.glob-changed-files-paths-fallback.outputs.paths-json }}

      - run: rm -rf .git
      - uses: ./
        name: Run int128/glob-changed-files-action without actions/checkout
        id: glob-changed-files-without-actions-checkout
        with:
          paths: |
            **
      - run: test "$CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ steps.glob-changed-files-without-actions-checkout.outputs.paths }}

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm run check --fix
      - uses: int128/update-generated-files-action@d9aac571db84cee6c16fa20190621e9deb2bc575 # v2.67.0
